### ISSUE TITLE
Doesn't Compile on Windows

### ISSUE THREAD

**Issue by hrzafer** [somebee/imba#11]
I'm using win-7 64-bit. I installing imba with npm gave the follwing output:

```
E:\workspace\npm>npm install -g imba
npm WARN optional dep failed, continuing fsevents@0.3.8
C:\Users\hrzafer\AppData\Roaming\npm\imba -> C:\Users\hrzafer\AppData\Roaming\np
m\node_modules\imba\bin\imba
imba@0.11.5 C:\Users\hrzafer\AppData\Roaming\npm\node_modules\imba
├── commander@2.8.1 (graceful-readlink@1.0.1)
├── chalk@1.1.1 (ansi-styles@2.1.0, supports-color@2.0.0, escape-string-regexp@1
.0.3, strip-ansi@3.0.0, has-ansi@2.0.0)
└── chokidar@1.0.5 (arrify@1.0.0, path-is-absolute@1.0.0, is-glob@1.1.3, glob-pa
rent@1.2.0, async-each@0.1.6, is-binary-path@1.0.1, readdirp@1.4.0, anymatch@1.3
.0)
```
I think it is installed properly anyway

```
E:\workspace\npm>imba

  Usage: undefined [options] [command]
[...]

```

Then I created a directory, created another called src, copied hello.imba and tried to compile:
```
E:\workspace\npm>imba watch ./src
dirname E:\workspace\npm E:\workspace\npm\src
--- watch dir: E:\workspace\npm\src
--- write dir: \E:\workspace\npm\lib
fs.js:747
  return binding.mkdir(pathModule._makeLong(path),
                 ^
Error: ENOENT, no such file or directory 'E:\E:.'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:747:18)
    at ensureDir (C:\Users\hrzafer\AppData\Roaming\npm\node_modules\imba\lib\compiler\cli.js:202:8)
    at writeFile (C:\Users\hrzafer\AppData\Roaming\npm\node_modules\imba\lib\compiler\cli.js:333:3)
    at EventEmitter.<anonymous> (C:\Users\hrzafer\AppData\Roaming\npm\node_modules\imba\lib\compiler\cli.js:447:12)
    at EventEmitter.emit (events.js:118:17)
    at EventEmitter.<anonymous> (C:\Users\hrzafer\AppData\Roaming\npm\node_modules\imba\node_modules\chokidar\index.js:137:38)
    at EventEmitter.FSWatcher._emit (C:\Users\hrzafer\AppData\Roaming\npm\node_modules\imba\node_modules\chokidar\index.js:152:5)
    at EventEmitter.NodeFsHandler._handleFile (C:\Users\hrzafer\AppData\Roaming\npm\node_modules\imba\node_modules\chokidar\lib\nodefs-handler.js:275:10)
    at EventEmitter.<anonymous> (C:\Users\hrzafer\AppData\Roaming\npm\node_modules\imba\node_modules\chokidar\lib\nodefs-handler.js:468:21)
```

I also tried to copying imba.js to the same place with src, tried again and got this error message window:

![capture](https://cloud.githubusercontent.com/assets/4048197/9402573/6e5ab25a-47e7-11e5-8d1e-7c0728f3cd6f.PNG)

**Comment by marvinroger** [comment]
The second Windows error you're having is not related to imba, it's just that the script was loaded not with node but with Windows Script Host.

**Comment by hrzafer** [comment]
Then imba.js shouldn't be in the same directory where "src" directory exists. Am I right?

**Comment by Ank1996** [comment]
I am using win-8 64-bit,and I had the same problem.

**Comment by marvinroger** [comment]
I will look at it tonight, I've had similar problems while watching fs on Windows. I'll try to submit a PR!

**Comment by Ank1996** [comment]
I am looking forward to it.:-D

**Comment by somebee** [comment]
Should be fixed on master - but won't be able to publish to npm before tomorrow. If possible you could try to install with npm from the repo.

**Comment by marvinroger** [comment]
I will report in a few hours.

**Comment by marvinroger** [comment]
I confirm everything is working on master. Thanks for the quick fix!

**Comment by somebee** [comment]
@marvinroger Thanks for testing. Neither of the core team (me and @judofyr) are on Windows, so it's great to have someone testing it out and reporting bugs. I'd be surprised if there aren't more platform specific bugs. I've pushed v0.11.6 to npm now with the fixes for watch.
