### ISSUE TITLE
Inheritance doesn't work

### ISSUE THREAD

**Issue by soaresderik** [somebee/imba#133]
When I try to apply inheritance, an error appears and does not point to the line where it occurred. Can someone help me?

```rb
class Animal 

	def initialize name
		@name = name

	def move meters
		console.log "{@name} moveu {meters}m."


class Snake < Animal
	def move
		console.log "Rastejando..."
		super 5
```

Error appearing

```
module.js:550
    throw err;
    ^

Error: Cannot find module 'imba'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Derik Soares\Documents\IMBA\first.imba:1:85)
    at Module._compile (module.js:653:30)
    at Object.exports.run.self.run (C:\Users\Derik Soares\AppData\Roaming\npm\node_modules\imba\lib\compiler\index.js:49:15)
    at Object.exports.run.self.run (C:\Users\Derik Soares\AppData\Roaming\npm\node_modules\imba\lib\cli\imba.js:65:15)
    at Object.<anonymous> (C:\Users\Derik Soares\AppData\Roaming\npm\node_modules\imba\bin\imba:6:28)
    at Module._compile (module.js:653:30)
```

**Comment by somebee** [comment]
How are you running this? The runtime shouldn't really be needed for subclasses/inheritance anymore (after es6), but Imba classes are still compiled to es3, and uses a helper. If you compile the file using `imbac --inline-helpers myfile.imba` you should be fine. But when you start using tags, the Imba runtime will be needed :)

So, either use ` --inline-helpers` or do `yarn add imba` (or `npm install imba`) in your project.

**Comment by soaresderik** [comment]
I was trying to run the get start examples with the command `imba filename.imba`. After I compiled it with the command `imbac --inline-helpers myfile.imba` it worked. Thank you very much
