### ISSUE TITLE
SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by danieldaeschle** [somebee/imba#138]
I'm on windows.
When i use imbapack i get this error:

```
..\Projects\Test\imba-test\node_modules\.bin\imbapack:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at requireConfig (C:\Users\i01002704\AppData\Roaming\npm\node_modules\webpack\bin\convert-argv.js:97:18)
```

**Comment by somebee** [comment]
Thanks for reporting. It's some sort of imbapack bug on windows. Until it is fixed you could use webpack directly as long as you add the imba loader in your config (see example https://github.com/somebee/hello-world-imba/blob/master/webpack.config.js)
